In [4]:
import numpy as np

In [7]:
print(np.version.version)

1.20.1


In [11]:
a = np.random.random((2,3,5))
a

array([[[0.67752708, 0.98495101, 0.68019902, 0.26075628, 0.38254903],
        [0.96080461, 0.75419127, 0.58343362, 0.52338944, 0.12143929],
        [0.91326628, 0.06367518, 0.68982045, 0.22623423, 0.71554117]],

       [[0.79762172, 0.47021665, 0.38929885, 0.20108452, 0.89578344],
        [0.78546989, 0.43255904, 0.29605205, 0.65048646, 0.4979804 ],
        [0.55244051, 0.21249332, 0.94844079, 0.57212456, 0.22120639]]])

In [14]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
a.size

30

In [17]:
b.size

30

In [20]:
a.shape

(2, 3, 5)

In [22]:
b.shape

(5, 2, 3)

In [23]:
a.ndim

3

In [25]:
b.ndim

3

In [27]:
b.transpose()

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [29]:
a.shape

(2, 3, 5)

In [31]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
c = np.reshape(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [43]:
b2 = b.transpose()
b2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [45]:
d = a+c
d

array([[[1.67752708, 1.98495101, 1.68019902, 1.26075628, 1.38254903],
        [1.96080461, 1.75419127, 1.58343362, 1.52338944, 1.12143929],
        [1.91326628, 1.06367518, 1.68982045, 1.22623423, 1.71554117]],

       [[1.79762172, 1.47021665, 1.38929885, 1.20108452, 1.89578344],
        [1.78546989, 1.43255904, 1.29605205, 1.65048646, 1.4979804 ],
        [1.55244051, 1.21249332, 1.94844079, 1.57212456, 1.22120639]]])

In [51]:
print(a)
print(d)

[[[0.67752708 0.98495101 0.68019902 0.26075628 0.38254903]
  [0.96080461 0.75419127 0.58343362 0.52338944 0.12143929]
  [0.91326628 0.06367518 0.68982045 0.22623423 0.71554117]]

 [[0.79762172 0.47021665 0.38929885 0.20108452 0.89578344]
  [0.78546989 0.43255904 0.29605205 0.65048646 0.4979804 ]
  [0.55244051 0.21249332 0.94844079 0.57212456 0.22120639]]]
[[[1.67752708 1.98495101 1.68019902 1.26075628 1.38254903]
  [1.96080461 1.75419127 1.58343362 1.52338944 1.12143929]
  [1.91326628 1.06367518 1.68982045 1.22623423 1.71554117]]

 [[1.79762172 1.47021665 1.38929885 1.20108452 1.89578344]
  [1.78546989 1.43255904 1.29605205 1.65048646 1.4979804 ]
  [1.55244051 1.21249332 1.94844079 1.57212456 1.22120639]]]


In [52]:
e = a*c
e

array([[[0.67752708, 0.98495101, 0.68019902, 0.26075628, 0.38254903],
        [0.96080461, 0.75419127, 0.58343362, 0.52338944, 0.12143929],
        [0.91326628, 0.06367518, 0.68982045, 0.22623423, 0.71554117]],

       [[0.79762172, 0.47021665, 0.38929885, 0.20108452, 0.89578344],
        [0.78546989, 0.43255904, 0.29605205, 0.65048646, 0.4979804 ],
        [0.55244051, 0.21249332, 0.94844079, 0.57212456, 0.22120639]]])

In [54]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [58]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("El valor maximo de 'd' es: ", d_max)
print("El valor minimo de 'd' es: ", d_min)
print("El promedio de 'd' es: ", d_mean)


El valor maximo de 'd' es:  1.984951012879347
El valor minimo de 'd' es:  1.063675180412697
El promedio de 'd' es:  1.5487012176355996


In [61]:
f = np.empty((2,4,5))
f

array([[[ 4.24399158e-314,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000, -8.15824090e-311,  2.95929617e+203,
          3.98576416e-038,  6.01334510e-154],
        [-1.25635059e-310,  4.62857235e-072,  1.05963508e-153,
          2.95967890e+203,  2.61211041e-033]],

       [[ 6.01334510e-154,  6.01347002e-154,  3.03338118e-067,
         -8.79059753e-311,  4.24399158e-314],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [-9.48024571e-311,  6.32264832e+233,  1.02215496e-234,
          4.14647719e+185, -1.43481042e-310]]])

In [66]:
for primer_arreglo in f:
    for segundo_arreglo in primer_arreglo:
        for tercer_arreglo in segundo_arreglo:
            if tercer_arreglo > d_min and tercer_arreglo < d_mean:
                tercer_arreglo = 25
f                

array([[[ 4.24399158e-314,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000, -8.15824090e-311,  2.95929617e+203,
          3.98576416e-038,  6.01334510e-154],
        [-1.25635059e-310,  4.62857235e-072,  1.05963508e-153,
          2.95967890e+203,  2.61211041e-033]],

       [[ 6.01334510e-154,  6.01347002e-154,  3.03338118e-067,
         -8.79059753e-311,  4.24399158e-314],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [-9.48024571e-311,  6.32264832e+233,  1.02215496e-234,
          4.14647719e+185, -1.43481042e-310]]])

In [67]:
d[(np.where((d > d_min) & (d < d_mean)))]

array([1.26075628, 1.38254903, 1.52338944, 1.12143929, 1.22623423,
       1.47021665, 1.38929885, 1.20108452, 1.43255904, 1.29605205,
       1.4979804 , 1.21249332, 1.22120639])